### ISSUE TITLE
Week 2 Out of Class : Review Online Presentations

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team1#2]
[(GDrive](https://drive.google.com/drive/folders/1pMy1A4UqZ5QNUOFguOyWY44RzVsFFfDA?usp=sharing) Folder for Week 2)

- Why use hills to define your work?
- Week 2 Assignment

[August 25 Class Recording](https://iit-edu.zoom.us/rec/share/a69hQe4ELAC971G5ZLqF6d0pJokVsPuRytA9aRGTrpaafB67iTDTIGA5_ZfmLuhQ.KLxNsZpYwnBKGipm?startTime=1629937772000)

**Comment by UjjwalAS** [comment]
Hi Adam,
I am sorry to ask this if you have already sent this. Where can I find the password to the zoom recording of last class.

**Comment by akallish** [comment]
> Hi Adam,
> I am sorry to ask this if you have already sent this. Where can I find the password to the zoom recording of last class.

@UjjwalAS Hello! If you look above, you will see the link for "Class Recording" That will take you to the Zoom recording.

**Comment by Tosgirl** [comment]
@UjjwalAS were you able to view the class recording? I am trying to view but it's asking for passcode @akallish
