### ISSUE TITLE
Week 2 Out of Class : Who are we as a team? Mural

### ISSUE THREAD

**Issue by akallish** [IITIDIDX597/F2021_Team1#3]
You have been assigned a team. Right now you are a group of individuals that is not interdependent yet. 

So you need to come together and share key quantitative and qualitative information about each other. But these are facts and you need to discuss what they mean to each other.

This is the start to begin a rapport and to learn to trust each other because each of you have shared and unique experiences and talents that can help you understand your team’s talent density.

[Mural Board](https://bit.ly/3CS39tA)

**Comment by akallish** [comment]
@UjjwalAS, @Tosgirl, @kreiser2 If it is started, then someone in your team should go to the Kanban and move this item into "In Progress."

If there are any questions about it, put it in this issue and "@" the appropriate people to respond. 

Thanks. @akallish

**Comment by akallish** [comment]
@UjjwalAS, @Tosgirl, @kreiser2 If it is started, then someone in your team should go to the Kanban and move this item into "In Progress."

If there are any questions about it, put it in this issue and "@" the appropriate people to respond. 

Thanks. @akallish

**Comment by UjjwalAS** [comment]
Hi Adam,
We have moved the issues that we started working into - In progress

**Comment by akallish** [comment]
> Hi Adam,
> We have moved the issues that we started working into - In progress

@UjjwalAS Yes! I credited your team in Slack as being the first team to move things in your Kanban. Congratulations.
